### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by The-Forecaster** [IUDevman/Tensor#63]
Can you pls add kotlin??

I like kotlin and it would be nice

![kiss](https://user-images.githubusercontent.com/56243908/147530385-13ce7959-78ec-46b0-b7d7-c10e5623dbe5.jpg)

**Comment by srgantmoomoo** [comment]
ill add kotlin to ur mom

**Comment by IUDevman** [comment]
Shouldn't be to hard to add it yourself since Kotlin is so technically challenging!!!
